### ISSUE TITLE
Cannot search for mods in mod filter list | Theme defaults to "custom" with many visual bugs at every startup, no matter what the precedent theme choice

### ISSUE THREAD

**Issue by tyrael93** [fn2006/PollyMC#19] opened 2022-08-17 13:27 UTC
### Operating System

Linux

### Version of PollyMC

PollyMC 1.4.1-94b1df22

### Version of Qt

Qt 5.12.8

### Description of bug

Like it says on the tin. With the newest version I'm greeted by

![theme](https://user-images.githubusercontent.com/5557920/185143744-3aa895e8-e56d-4b68-b753-0f3354172c28.png) 

and

![Screenshot from 2022-08-17 16-17-20](https://user-images.githubusercontent.com/5557920/185143958-9649056f-7df0-4ebc-b9de-2a1a02c51634.png)

and an empty instance icon. Everything gets fixed the moment I change the theme.

![Screenshot from 2022-08-17 16-18-37](https://user-images.githubusercontent.com/5557920/185144171-5e35009a-a37b-4bb5-803e-2942cf8f3ca1.png)

Searching mods in the filter tab is also broken, but in a much more complicated way. It varies wildly, sometimes it works, sometimes it gives false negatives, the vast majority of the time it outright doesn't work.

![Screenshot from 2022-08-17 16-21-36](https://user-images.githubusercontent.com/5557920/185145109-b2624b3e-502d-49df-bcdb-6d8a7ec53d74.png)
![Screenshot from 2022-08-17 16-22-54](https://user-images.githubusercontent.com/5557920/185145255-c5b26c9a-ff31-4142-ada5-c55c6d5bcb8d.png)

I remember Poly had some issues with the search bar not working altogether, it might be related to that. No clue about the borked theme. 

Nothing gamebreaking, but both very annoying to deal with, especially the mod filter.

Thank you in advance with any help on the subject.

### Steps to reproduce

Start PollyMC 1.4.1.1 and look at the theme.
Search for mods in an instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment] 2022-08-17 17:49
I'm not really sure what's happening with the mod filtering but I think the broken themes are caused by you not having qt5-svg installed, the package name is `qt5-svg` on Arch-based distros and `libqt5svg5` on Ubuntu-based distros, not sure about other distros.

**Comment by tyrael93** [comment] 2022-08-17 19:12
Thanks for the fast reply! Also, I really hate to be that guy :cry: but that doesn't seem to be the case, I already have libqt5svg5 installed and it's still doing its thing.
![Screenshot from 2022-08-17 22-06-35](https://user-images.githubusercontent.com/5557920/185222883-a34614d7-cf1f-444b-af79-83caf9fb1243.png)

I'm not particularly sure what's happening here either, maybe it's something that will get fixed in the next release with the next upstream merge, in the meantime I think I can just use my old version of poly until my mojang accounts get completely phased out.

**Comment by fn2006** [comment] 2022-08-17 19:29
Interesting, do the themes work in regular PolyMC?

**Comment by tyrael93** [comment] 2022-08-17 19:45
Oh yeah, everything's peachy in the portable version of Poly for some reason. I had stayed on 1.3.2 and skipped 1.4.0 because of the mod filter issue being completely unresponsive, but 1.4.1 works great. I'm really not sure why this is happening with Polly 1.4.1 portable, maybe some divergent commit from the source of some sort? I've just did a second check by re-downloading PollyMC-Linux-Portable-1.4.1.1 just to make sure I didn't goof and download the Qt6 version by accident, but no, it's right there out of the box.

**Comment by fn2006** [comment] 2022-08-17 19:56
That's really weird, I'll try to figure out what's wrong with it later.

**Comment by fn2006** [comment] 2022-08-19 14:32
Alright, I've remerged my changes into the latest PolyMC, please could you try this build: https://github.com/fn2006/PollyMC/suites/7890375568/artifacts/335288565

**Comment by tyrael93** [comment] 2022-08-19 17:20
Nope, same thing sadly. 
I'm pretty sure that just means that it's a me thing. 
I'll just close the issue, if someone else ever comes out with a similar problem, then I can just reference it. I'll try to also test the Qt6 version instead of Qt5 and see if that fixes the issue.

Thanks for all the help!

**Comment by fn2006** [comment] 2022-08-19 20:51
It's not just a problem with your machine, I can reproduce it in a Linux Mint 20.3 VM, Mint 21 works fine though.

**Comment by tyrael93** [comment] 2022-08-19 20:54
Huh. Looks like I need to update then.

**Comment by tyrael93** [comment] 2022-09-17 06:37
Oh man, this is embarrassing. I finally found out what the issue was with the search.
![goddamnit](https://user-images.githubusercontent.com/5557920/190844040-3edc9b3d-ee1c-4ddf-8304-582a42be6dac.png)

It's case sensitive. That was the issue.
I don't remember it being case sensitive in the old versions, and there is no option to actually disable that, but between the upgrade fixing the interface (I haven't yet updated, but I just noticed that poly 1.4.2 also has this issue, so it definitely isn't a polly-only problem and I just need to get the update over and done with :sweat: ) and the search working all along, I think we can safely say we've managed to fix all the issues. Let me know if this can be closed!

**Comment by fn2006** [comment] 2022-09-17 14:04
Ah, at least you figured it out, I think I'll close this because the theming issue exists upstream (https://github.com/PolyMC/PolyMC/issues/1009) and the search issue was actually user error (I don't think mod searching should be case sensitive though, I might open an issue upstream).

**Closed by fn2006** 2022-09-17 14:04 UTC
Labels: bug

**Comment by tyrael93** [comment] 2022-09-26 06:35
Just chiming in again to point out that after updating to el minto 21 the filter list is not case-sensitive anymore. Go figure!

Also I can confirm that the themes work properly now. Thanks for all the help on this! :muscle:
